# Tracing: file changing and reading in critical Linux full paths (from AuditD config Neo23x0 + KUMA Community)

apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "file-change-read-monitoring-filtered-fullpath"
spec:
  kprobes:
  - call: "security_file_permission"
    syscall: false
    return: true
    args:
    - index: 0
      type: "file" # (struct file *) used for getting the path
    - index: 1
      type: "int" # 0x04 is MAY_READ, 0x02 is MAY_WRITE
    returnArg:
      index: 0
      type: "int"
    returnArgAction: "Post"
    selectors:
    - matchArgs:
      - index: 0
        operator: "Equal"
        values:
        - "/etc/aliases"
        - "/etc/bash.bash_logout"
        - "/etc/bash.bashrc"
        - "/etc/bashrc"
        - "/etc/cron.allow"
        - "/etc/cron.deny"
        - "/etc/crontab"
        - "/etc/csh.cshrc"
        - "/etc/csh.login"
        - "/etc/dnf/plugins/dnfcon.conf"
        - "/etc/docker"
        - "/etc/environment"
        - "/etc/group"
        - "/etc/gshadow"
        - "/etc/hostname"
        - "/etc/hosts"
        - "/etc/inittab"
        - "/etc/issue"
        - "/etc/ld.so.conf"
        - "/etc/ld.so.preload"
        - "/etc/localtime"
        - "/etc/login.defs"
        - "/etc/modprobe.conf"
        - "/etc/pacman.conf"
        - "/etc/pam.d/common-password"
        - "/etc/pam.d/password-auth"
        - "/etc/pam.d/system-auth"
        - "/etc/passwd"
        - "/etc/profile"
        - "/etc/rc.local"
        - "/etc/salt"
        - "/etc/securetty"
        - "/etc/security/limits.conf"
        - "/etc/security/namespace.conf"
        - "/etc/security/namespace.init"
        - "/etc/security/opasswd"
        - "/etc/security/pam_env.conf"
        - "/etc/security/pwquality.conf"
        - "/etc/shadow"
        - "/etc/shells"
        - "/etc/ssh/sshd_config"
        - "/etc/sudoers"
        - "/etc/sysconfig/docker"
        - "/etc/sysconfig/docker-storage"
        - "/etc/sysctl.conf"
        - "/etc/systemd/system"
        - "/etc/systemd/system-generators"
        - "/etc/systemd/user"
        - "/etc/systemd/user-generators"
        - "/lib/systemd/system"
        - "/lib/systemd/system-generators"
        - "/lib/systemd/user"
        - "/lib64/dbus-1/dbus-daemon-launch-helper"
        - "/lib64/vte-2.91/gnome-pty-helper"
        - "/root/.bash_login"
        - "/root/.bash_logout"
        - "/root/.bash_profile"
        - "/root/.bashrc"
        - "/root/.profile"
        - "/root/.ssh/authorized_keys"
        - "/root/.ssh/known_hosts"
        - "/run/systemd/system"
        - "/run/systemd/system-generators"
        - "/run/systemd/user"
        - "/run/systemd/user-generators"
        - "/usr/lib/systemd"
        - "/usr/lib/systemd/system"
        - "/usr/lib/systemd/system-generators"
        - "/usr/lib/systemd/system/docker.service"
        - "/usr/lib/systemd/system/docker.socket"
        - "/usr/lib/systemd/user"
        - "/usr/lib/systemd/user-generators"
        - "/usr/lib64/dbus-1/dbus-daemon-launch-helper"
        - "/usr/lib64/vte-2.91/gnome-pty-helper"
        - "/usr/libexec/kde4/kdesud"
        - "/usr/libexec/kde4/kpac_dhcp_helper"
        - "/usr/libexec/sssd/krb5_child"
        - "/usr/libexec/sssd/ldap_child"
        - "/usr/libexec/sssd/p11_child"
        - "/usr/libexec/sssd/proxy_child"
        - "/usr/libexec/sssd/selinux_child"
        - "/usr/local/etc/salt"
        - "/usr/local/lib/systemd/system-generators"
        - "/usr/local/share/systemd/user"
        - "/usr/share/systemd/user"
      - index: 1
        operator: "Equal"
        values:
        - "2" # MAY_WRITE
    - matchArgs:
      - index: 0
        operator: "Equal"
        values:
        - "/etc/aliases"
        - "/etc/bash.bash_logout"
        - "/etc/bash.bashrc"
        - "/etc/bashrc"
        - "/etc/cron.allow"
        - "/etc/cron.deny"
        - "/etc/crontab"
        - "/etc/csh.cshrc"
        - "/etc/csh.login"
        - "/etc/dnf/plugins/dnfcon.conf"
        - "/etc/docker"
        - "/etc/environment"
        - "/etc/group"
        - "/etc/gshadow"
        - "/etc/hostname"
        - "/etc/hosts"
        - "/etc/inittab"
        - "/etc/issue"
        - "/etc/ld.so.conf"
        - "/etc/ld.so.preload"
        - "/etc/localtime"
        - "/etc/login.defs"
        - "/etc/modprobe.conf"
        - "/etc/pacman.conf"
        - "/etc/pam.d/common-password"
        - "/etc/pam.d/password-auth"
        - "/etc/pam.d/system-auth"
        - "/etc/passwd"
        - "/etc/profile"
        - "/etc/rc.local"
        - "/etc/salt"
        - "/etc/securetty"
        - "/etc/security/limits.conf"
        - "/etc/security/namespace.conf"
        - "/etc/security/namespace.init"
        - "/etc/security/opasswd"
        - "/etc/security/pam_env.conf"
        - "/etc/security/pwquality.conf"
        - "/etc/shadow"
        - "/etc/shells"
        - "/etc/ssh/sshd_config"
        - "/etc/sudoers"
        - "/etc/sysconfig/docker"
        - "/etc/sysconfig/docker-storage"
        - "/etc/sysctl.conf"
        - "/etc/systemd/system"
        - "/etc/systemd/system-generators"
        - "/etc/systemd/user"
        - "/etc/systemd/user-generators"
        - "/lib/systemd/system"
        - "/lib/systemd/system-generators"
        - "/lib/systemd/user"
        - "/lib64/dbus-1/dbus-daemon-launch-helper"
        - "/lib64/vte-2.91/gnome-pty-helper"
        - "/root/.bash_login"
        - "/root/.bash_logout"
        - "/root/.bash_profile"
        - "/root/.bashrc"
        - "/root/.profile"
        - "/root/.ssh/authorized_keys"
        - "/root/.ssh/known_hosts"
        - "/run/systemd/system"
        - "/run/systemd/system-generators"
        - "/run/systemd/user"
        - "/run/systemd/user-generators"
        - "/usr/lib/systemd"
        - "/usr/lib/systemd/system"
        - "/usr/lib/systemd/system-generators"
        - "/usr/lib/systemd/system/docker.service"
        - "/usr/lib/systemd/system/docker.socket"
        - "/usr/lib/systemd/user"
        - "/usr/lib/systemd/user-generators"
        - "/usr/lib64/dbus-1/dbus-daemon-launch-helper"
        - "/usr/lib64/vte-2.91/gnome-pty-helper"
        - "/usr/libexec/kde4/kdesud"
        - "/usr/libexec/kde4/kpac_dhcp_helper"
        - "/usr/libexec/sssd/krb5_child"
        - "/usr/libexec/sssd/ldap_child"
        - "/usr/libexec/sssd/p11_child"
        - "/usr/libexec/sssd/proxy_child"
        - "/usr/libexec/sssd/selinux_child"
        - "/usr/local/etc/salt"
        - "/usr/local/lib/systemd/system-generators"
        - "/usr/local/share/systemd/user"
        - "/usr/share/systemd/user"
      - index: 1
        operator: "Equal"
        values:
        - "4" # MAY_READ